### ISSUE TITLE
部署完，测了全是0，按理说不应该不可能一个流媒体都不解锁啊。

### ISSUE THREAD

**Issue by heaid** [thank243/StairUnlocker-Bot#31]
![](https://images.weserv.nl/?url=https://article.biliimg.com/bfs/article/5a588de9b38f316b0ef4a04d64328775ab4ecffd.png)

既然能生成图片表示我搭建的也没啥问题吧，我用的subconverter   docker 后端，

**Comment by thank243** [comment]
You can use the demo [bot](https://t.me/stairunlock_test_bot) for testing. Remember turn on debug mode and paste more debug logs. That is an effective way to locate your problem.

**Comment by heaid** [comment]
我猜测，有可能是因为节点用了国内中转，而部署的服务器是在香港，香港没法通过国内服务器的入口ip来检测，毕竟入口一般都已经屏蔽海外了

**Comment by heaid** [comment]
我使用印度直连测试了下，上图是印度 部署warp ipv6 解锁Netflix ，下图是部署warp 双栈解锁Netflix
貌似如果vps是通过ipv6解锁的就检测不出来，另外检测Netflix的网页链接可能失效了，
用lmc999的检测地址是https://www.netflix.com/title/81280792

![https://images.weserv.nl/?url=https://article.biliimg.com/bfs/article/71799e284fc772f572f33793b10ffc4d70c7f1d9.png]

vps解锁图 使用脚本

```
 bash <(curl -L -s https://raw.githubusercontent.com/lmc999/RegionRestrictionCheck/main/check.sh)
```
![](https://images.weserv.nl/?url=https://article.biliimg.com/bfs/article/1f23bd15a66baee16e973ae52170d25a3ae828c5.png)

**Comment by heaid** [comment]
如果是这样那么貌似只要是部署在国外，加了国内中转的节点就没法检测了，但是如果部署在国内，tg机器人又连不上，或者使用workers路由反代tgapi（或者自行中转tgapi），部署在国内机器或许能行？不知道我猜测是否正确

**Comment by thank243** [comment]
You can use the demo bot to compare result. Use /ip command to test connectivity. Only netflix full unlock will be show.

**Comment by heaid** [comment]
结果一模一样

**Comment by thank243** [comment]
The possible reason could be your nodes block overseas IPs.
